### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by no1san** [ZeroX-DG/SnippetStore#56] opened 2020-01-12 09:16 UTC
Hi,
maybe it is just a user problem but:
How do I add any Tag to my snippet?

**Comment by ZeroX-DG** [comment] 2020-01-12 22:12
Hi, you can click edit on your snippet and type in the tags in the input next to the tag icon

**Comment by no1san** [comment] 2020-01-13 09:55
Thanks for your fast reply.
I tried that. I can enter a tag however they are not saved.

**Comment by Echowxsy** [comment] 2020-02-15 16:42
> Thanks for your fast reply.
> I tried that. I can enter a tag however they are not saved.

maybe you need type a blank after type tag name

**Comment by ndsamuelson** [comment] 2020-03-11 19:13
> > Thanks for your fast reply.
> > I tried that. I can enter a tag however they are not saved.
> 
> maybe you need type a blank after type tag name

This is correct. I wasn't able to duplicate the issue. Try re-installing. 💪

**Comment by i-ce-fish** [comment] 2020-08-11 07:44
You should press TAB after input a  tag

**Comment by ZeroX-DG** [comment] 2020-09-02 00:27
I can't reproduce the issue either. I'll close this issue thanks for reporting anyway :+1:

**Closed by ZeroX-DG** 2020-09-02 00:27 UTC
